spring.application.name=guess

spring.ai.vertex.ai.gemini.project-id=howmuch-494401

spring.ai.vertex.ai.gemini.location=us-central1

spring.ai.vertex.ai.gemini.chat.options.model=gemini-2.5-pro

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
